version: '3.7'

services:
  server:
    container_name: douchebag_server
    image: douche_bag:v1.0
  client:
    container_name: douchebag_client
    image: nginx
    volumes:
      - ./nginx/nginx6.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    depends_on:
      - server